[project]
name = "artEmotion"
version = "0.1.0"
description = "Here you can convert your emotions to art"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "langchain-google-genai>=2.0.7",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.34.0",
]
